config/routes.rb
Rails.application.routes.draw do
  resources :maplocations
  resources :reviews
  resources :purchases
  resources :books, :authors
  mount Monologue::Engine, at: '/blog'
  devise_for :users, controllers: {sessions: 'users/sessions'}
  root to: 'books#index'

  match 'contact' => 'contact#new', :as => 'contact1', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  
end

app/models/maplocation.rb
class Maplocation < ActiveRecord::Base

    geocoded_by :address
    after_validation :geocode, :if => :address_changed?


end

app/controllers/maplocations_controller.rb
class MaplocationsController < ApplicationController

  skip_before_action :authenticate_user!
  
  before_action :set_maplocation, only: [:show, :edit, :update, :destroy]

  

  # GET /maplocations
  # GET /maplocations.json
  def index
    @maplocations = Maplocation.all
  end

  # GET /maplocations/1
  # GET /maplocations/1.json
  def show
  end

  # GET /maplocations/new
  def new
    @maplocation = Maplocation.new
  end

  # GET /maplocations/1/edit
  def edit
  end

  # POST /maplocations
  # POST /maplocations.json
  def create
    @maplocation = Maplocation.new(maplocation_params)

    respond_to do |format|
      if @maplocation.save
        format.html { redirect_to @maplocation, notice: 'Maplocation was successfully created.' }
        format.json { render :show, status: :created, location: @maplocation }
      else
        format.html { render :new }
        format.json { render json: @maplocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maplocations/1
  # PATCH/PUT /maplocations/1.json
  def update
    respond_to do |format|
      if @maplocation.update(maplocation_params)
        format.html { redirect_to @maplocation, notice: 'Maplocation was successfully updated.' }
        format.json { render :show, status: :ok, location: @maplocation }
      else
        format.html { render :edit }
        format.json { render json: @maplocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maplocations/1
  # DELETE /maplocations/1.json
  def destroy
    @maplocation.destroy
    respond_to do |format|
      format.html { redirect_to maplocations_url, notice: 'Maplocation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maplocation
      @maplocation = Maplocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maplocation_params
      params.require(:maplocation).permit(:address, :latitude, :longitude)
    end
end

app/helpers/maplocations_helper.rb
module MaplocationsHelper
end

app/views/maplocations/_form.html.erb
<%= form_for(@maplocation) do |f| %>
  <% if @maplocation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@maplocation.errors.count, "error") %> prohibited this maplocation from being saved:</h2>

      <ul>
      <% @maplocation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <% f.label :latitude %><br>
    <% f.text_field :latitude %>
  </div>
  <div class="field">
    <% f.label :longitude %><br>
    <% f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit 'Show Map' %>
  </div>
<% end %>

app/views/maplocations/edit.html.erb
<h1>Editing Maplocation</h1>

<%= render 'form' %>

<%= link_to 'Show', @maplocation %> |
<%= link_to 'Back', maplocations_path %>

app/views/maplocations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Maplocations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maplocations.each do |maplocation| %>
      <tr>
        <td><%= maplocation.address %></td>
        <td><%= maplocation.latitude %></td>
        <td><%= maplocation.longitude %></td>
        <td><%= link_to 'Show', maplocation %></td>
        <td><%= link_to 'Edit', edit_maplocation_path(maplocation) %></td>
        <td><%= link_to 'Destroy', maplocation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Maplocation', new_maplocation_path %>

app/views/maplocations/new.html.erb
<h1>City Library</h1>



<% @city = request.location.city %><br>
<% @state = request.location.state %><br>



<% @maplocation.address = "Library #{@city}  #{@state}" %>


<%= render 'form' %>


<%= link_to 'Back', books_path(params[:book_id]) %>    

app/views/maplocations/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Address:</strong>
  <%= @maplocation.address %>
</p>


<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@maplocation.latitude}%2C#{@maplocation.longitude}" %> 
<br>

<p>
  Distance from your location to city library is 
  <% result = request.location %>    
  <%= @maplocation.distance_to(result.address).round(2) %> miles
</p>