config/routes.rb
Rails.application.routes.draw do
  resources :maplocations
  resources :reviews
  resources :purchases
  resources :books, :authors
  mount Monologue::Engine, at: '/blog'
  devise_for :users, controllers: {sessions: 'users/sessions'}
  root to: 'books#index'

  match 'contact' => 'contact#new', :as => 'contact1', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  before_action :authenticate_user!
  
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json



  def create_anymos
    @purchase = Purchase.new
    @purchase.user_id = @user.user_id
    @purchase.book_id = @book.book_id
    @purchase.quantity = 1
    @purchase.date = date
    @purchase.save
    
    helper_method :create_anymos

  end


  def create
    @purchase = Purchase.new(purchase_params)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:user_id, :book_id, :quantity, :date)
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form.html.erb
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset disabled>
    <div class="form-group">
      <%= f.label :user_id %><br>
      <%= f.select :user_id, User.all.collect {|p| [p.email, p.id]}, include_blank: true %>
      
    </div>
    <div class="form-group">
      <%= f.label :book_id %><br>
      <%= f.select :book_id, Book.all.collect {|p| [p.title, p.id]}, include_blank: true %> 
      
    </div>
  </fieldset>
  <div class="form-group">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit "Confrim Purchase", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing Purchase</h1>


<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Purchases</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Book</th>
      <th>Quantity</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.user_id %></td>
        <td><%= purchase.book_id %></td>
        <td><%= purchase.quantity %></td>
        <td><%= purchase.date %></td>
        <td><%= link_to 'Show', purchase %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<% @purchase.user_id = current_user.id %>
<% @purchase.book_id = params[:book_id] %>
<% @purchase.quantity = 1 %>
<% @purchase.date = Date.today %>

<%= render 'form' %>

<% if params[:book_id].present? %>
    <%= link_to 'Back', book_path(params[:book_id]) %>    
<% else %>
    <%= link_to 'Back', purchases_path %>
<% end %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @purchase.user_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @purchase.book_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @purchase.quantity %>
</p>

<p>
  <strong>Date:</strong>
  <%= @purchase.date %>
</p>


<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<%= link_to 'Back', books_path %>