config/routes.rb
Rails.application.routes.draw do
  resources :maplocations
  resources :reviews
  resources :purchases
  resources :books, :authors
  mount Monologue::Engine, at: '/blog'
  devise_for :users, controllers: {sessions: 'users/sessions'}
  root to: 'books#index'

  match 'contact' => 'contact#new', :as => 'contact1', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/new.html.erb
<%=  form_for @message, :url => contact_path do |form| %>
  <fieldset class="form-group">
    <div class="form-group">
      <%= form.label :name, class:"control-label col-sm-2" %>
      <%= form.text_field :name %>
    </div>
    
    <div class="form-group">
      <%= form.label :email , class:"control-label col-sm-2" %>
      <%= form.text_field :email %>
    </div>
    <div class="form-group">
      <%= form.label :subject , class:"control-label col-sm-2" %>
      <%= form.text_field :subject %>
    </div>
    
    <div class="form-group">
      <%= form.label :body , class:"control-label col-sm-2" %>
      <%= form.text_area :body %>
    </div>
  </fieldset>
  
  <fieldset class="actions">
    <%= form.submit "Send", class:"btn btn-success" %>
    <%= link_to "Cancel", books_path, class:"btn btn-default"%>
  </fieldset>
<% end %>